### PR TITLE
Proposal to fix issue #1

### PR DESCRIPTION
**Pull request by nvdaes**

### CODE REVIEW

**Comment by jasonjgw** [comment]
I think this change should be merged. I reviewed the description of accessMode on the W3C wiki, but it didn't define "textual" as clearly as I would have preferred. Perhaps I was looking in the wrong place, though.

**Comment by nvdaes** [comment]
jasonjgw commented: 
...

> I reviewed the description of accessMode on the W3C wiki, but it didn't define "textual" as clearly as I would have preferred.

Textual may not be clearly defined. Anyway, it's not equivalent to visual, since text could be read in braille, with eyes or speech.
I found this at

http://kb.daisy.org/publishing/docs/metadata/schema-org.html

> If the images are also adequately described (alt text and extended descriptions, as appropriate) a single textual mode would also be sufficient, indicating someone who is blind can consume the content.

This shows that textual is not visual, and also it's shown by the fact that they are separate access modes which can be combined.
Anyway, I don't know if the expression "textual abilities", used in other part of the guide, is precisse or should be clarified, for instance adding something like (the text maybe read in braille, speech, enlarged, etc).
Visual, tactile and auditory correspond directly with sensory capabilities, but textual is wider, though I think it's understandable.

**Review by clapierre — APPROVED** [review]
Totally agree with this, nice catch.

**Comment by nvdaes** [comment]
clapierre left a comment 

> Totally agree with this, nice catch.

Thanks for your great work.

**Pull request merged**
